### ISSUE TITLE
A t ho sZhou

### ISSUE THREAD

**Issue by hyber-athos** [Huangxunyiiii/Github-Bot-Test#7]
A t ho sZhou

**Comment by hyber-athos** [comment]
1.  2
2. 2
3. 3

- a s d
- 222

> asd

```
print("a")
```

# asd

/close

**Comment by huangxunyi** [comment]
@hyber-athos: closing this issue. 
 <details>

In response to [this](https://github.com/Huangxunyiiii/Github-Bot-Test/issues/7#issuecomment-683224658) 

1.  2
> 2. 2
> 3. 3
> 
> - a s d
> - 222
> 
> > asd
> 
> ```
> print("a")
> ```
> 
> # asd
> 
> /close
> 

...Hello world
</details>
